# Generated by Django 5.0.2 on 2025-11-08 06:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_memorycollection_memorymessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UIBuilderProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('components', models.JSONField(default=dict)),
                ('styles', models.JSONField(default=dict)),
                ('assets', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='credential',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflow',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='credential',
            index=models.Index(fields=['user', 'credential_type'], name='workflows_c_user_id_917615_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['user', '-created_at'], name='workflows_w_user_id_b7523e_idx'),
        ),
        migrations.AddField(
            model_name='uibuilderproject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ui_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='uibuilderproject',
            index=models.Index(fields=['user', '-updated_at'], name='workflows_u_user_id_25d6aa_idx'),
        ),
    ]
