# Generated by Django 5.0.2 on 2025-11-08 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_uibuilderproject_credential_user_workflow_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exportedworkflow',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exported_workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memorycollection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memory_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memorycollection',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='memorycollection',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='exportedworkflow',
            index=models.Index(fields=['user', '-exported_at'], name='workflows_e_user_id_8e39fa_idx'),
        ),
        migrations.AddIndex(
            model_name='memorycollection',
            index=models.Index(fields=['user', '-created_at'], name='workflows_m_user_id_fe5340_idx'),
        ),
    ]
